---
- name: add docker key
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: present
  become: true
- name: add docker repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ distro_repo }} stable'
    state: present
  become: true
- name: install docker stuff
  become: true
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
    cache_valid_time: 68400
# FIXME allow vagrant user to the current playbook - 'ControlPersist'. Use whoami to debug
- name: add 'vagrant' user to docker group
  become: true
  user:
    name: vagrant
    groups: docker
    append: true  
- name: init docker to systemd
  service:
    state: started
    name: docker
# sudo is required to install correctely sdk and use it with 'docker-image'    
- name: install 'docker' SDK for python
  become: true
  pip:
    name: docker
    state: present
- name: download 'docker-compose'
  become: true
  get_url:
    url: 'https://github.com/docker/compose/releases/download/1.25.5/docker-compose-Linux-x86_64'
    dest: '/usr/local/bin/docker-compose'
    mode: 0755