---
# sudo is required to install correctely the modules
- name: install 'flask' packages
  become: true
  pip:
    name: 
      - flask
      - flask-cors
    state: present
- name: copy 'microflask' service file
  copy:
    src: microflask.service
    dest: /lib/systemd/system/microflask.service
    owner: vagrant
  become: true
# FIXME allow without become, ConstantCache
- name: start 'microflask' service
  become: true
  service: 
    name: microflask
    state: started
    enabled: yes

# FIXME allow without become, ConstantCache
# - name: start 'microflask' service
#   become: true
#   systemd: 
#     name: microflask
#     state: started
#     daemon_reload: yes    