---
- name: install 'flask' packages
  pip:
    name: '{{ item }}'
    state: present
  with_items:
    - flask
    - flask-cors
- name: copy 'microflask' service file
  copy:
    src: microflask.service
    dest: /lib/systemd/system/microflask.service
    owner: vagrant
  become: true
# FIXME allow without become, ConstantCache
- name: start 'microflask' service
  become: true
  service: 
    name: microflask
    state: started
    enabled: yes