---
- name: install apt packages
  become: true
  apt: 
    pkg: 
      - nginx 
      - nodejs
      - npm
      - yarn
    state: present
    update_cache: true
    cache_valid_time: 3600
- name: install flask 
  pip:
    name: flask
- name: start nginx
  service: name=nginx state=started