---
- name: install nginx
  become: true
  apt: 
    name: nginx 
    state: present
    update_cache: true
    cache_valid_time: 604800
- name: start nginx
  service: 
    name: nginx
    state: started