---
- name: install required pkgs
  become: true
  apt:
    pkg:
      - unzip
    state: present
    update_cache: true
    cache_valid_time: 86400
- name: download and unarchive terraform {{ terraform_version }}
  become: true
  unarchive:
    src: 'https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip'
    dest: '/usr/local/bin'
    creates: '/usr/local/bin/terraform'
    remote_src: true
  register: result
  until: result is succeeded  
  retries: 8
  delay: 12
# - debug:
#     var: result.failed
# - command: echo "Hola mundo"
#   when: result is failed
# - command: echo "Hellow world"
#   when: result is succeeded  
#   # until: result is succeeded  
#   # retries: 5
#   # delay: 10
