---
- name: copy environment file
  copy:
    src: vars-environment.sh
    dest: '{{ env_folder }}/{{ env_filename }}'
  become: true
- name: add commands to env file
  become: true
  blockinfile:
    dest: '{{ env_folder }}/{{ env_filename }}'
    block: '{{ env_variables }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK - variables'
    insertafter: EOF
    create: true
- name: add aliases to bash
  blockinfile:
    dest: '/home/vagrant/.bashrc'
    block: '{{ bash_aliases_vm }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK - aliases'
    insertafter: EOF
    create: true    