---
- include: envfile.yml
- name: get distro_repo from VM
  when: distro_repo is not defined
  shell: lsb_release -cs
  register: distro_repo
- name: save 'distro_repo' fact
  set_fact:
    distro_repo: '{{ distro_repo.stdout }}'
    cacheable: yes
  