---
- name: update apt cache
  apt: 
    update_cache: true
    cache_valid_time: 129600
  become: true
- name: install common apt programs
  become: true
  apt:
    pkg: 
      - lsb-release
      # - python3-pip
    state: present
    update_cache: true
    cache_valid_time: 604800