---
- name: Install Development Stuff
  hosts: generalservers
  pre_tasks:
    - name: include secrets files
      include_vars:
        dir: secrets
        extensions: ['yml', 'yaml']
      no_log: true
  roles:
    - role: systemlib
    - role: common
    - role: terraform
    - role: webserver
    - role: deployment