---
- name: Install Development Stuff
  hosts: generalservers
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=7200
      become: true
    - name: include secrets files
      include_vars:
        dir: secrets
        extensions: ['yml', 'yaml']
      no_log: true
  roles:
    - role: common
    - role: webserver
    - role: deployment