---
- name: Install Development Stuff
  hosts: generalservers
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
      become: true
  roles:
    - role: common
    - role: webserver
    - role: deployment