---
- name: Install docker images
  hosts: generalservers
  pre_tasks:
    - name: include secrets files
      include_vars:
        dir: secrets
        extensions: ['yml', 'yaml']
      no_log: true
  roles:
    - role: docker-images